---
- name: Install containerd package
  package:
    name: "{{ _packages[ansible_os_family] }}"
    state: present
  vars:
    _packages:
      Debian:
        - containerd.io={{ containerd_version }}-*
      RedHat:
        - containerd.io-{{ containerd_version }}
  module_defaults:
    yum: {lock_timeout: "{{ yum_lock_timeout }}"}

- name: Configure prerequisites
  include_tasks: configure-prerequisites.yml

- name: Configure containerd
  include_tasks: configure-containerd.yml

- name: Provide crictl.yaml file
  copy:
    src: crictl.yaml
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: u=rw,go=r
