---
- name: Assert that update variable is defined
  assert:
    that:
      - update is defined
    fail_msg: Variable 'update' must be defined.

- name: Include set-cluster-version.yml
  include_tasks: set-cluster-version.yml

- name: Collect kubeadm-config from ConfigMap
  command: |
    kubectl get configmap kubeadm-config \
      --namespace kube-system \
      --output jsonpath={{ _jsonpath }}
  vars:
    _jsonpath: >-
      '{.data.ClusterConfiguration}'
  register: kubeadm_config
  changed_when: false

- name: Extend kubeadm config
  set_fact:
    kubeadm_config: >-
      {{ original | combine(update, recursive=true) }}
  vars:
    original: >-
      {{ kubeadm_config.stdout | from_yaml }}

- name: Collect kubelet-config from ConfigMap
  command: |-
    kubectl get cm kubelet-config-{{ cluster_version_major }}.{{ cluster_version_minor }} \
      --namespace kube-system \
      --output=jsonpath={{ _jsonpath }}
  vars:
    _jsonpath: >-
      '{.data.kubelet}'
  register: kubelet_config
  changed_when: false

- name: Render /etc/kubeadm/kubeadm-config.yml
  copy:
    dest: /etc/kubeadm/kubeadm-config.yml
    mode: u=rw,go=
    content: |
      {{ kubeadm_config | to_nice_yaml(indent=2) }}
      ---
      {{ kubelet_config.stdout | from_yaml | to_nice_yaml(indent=2) }}
