---
docker_daemon_defaults:
  exec-opts:
    - native.cgroupdriver=systemd
  insecure-registries:
    - "{{ image_registry_address }}"
  log-driver: json-file
  log-opts:
    # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
    max-size: 10m
    # The maximum number of log files that can be present.
    max-file: "2"  # must be a string

docker_version:
  Debian: "5:20.10.8*" # * is needed to match a version such as '5:19.03.14~3-0~ubuntu-bionic'
  RedHat: "20.10.8"

docker_packages:
  Debian:
    - containerd.io={{ containerd_defaults.containerd_version }}-*
    - docker-ce-cli={{ docker_version.Debian }}
    - docker-ce-rootless-extras={{ docker_version.Debian }}
    - docker-ce={{ docker_version.Debian }}
  RedHat:
    - containerd.io-{{ containerd_defaults.containerd_version }}
    - docker-ce-cli-{{ docker_version.RedHat }}
    - docker-ce-rootless-extras-{{ docker_version.RedHat }}
    - docker-ce-{{ docker_version.RedHat }}
